# Generated by Django 4.1.1 on 2022-09-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненты'},
        ),
    ]
